#install.packages("remotes")
#remotes::install_github("deepanshu88/shinyDarkmode")
library(shiny)
library(shinydashboard)
library(shinyWidgets)
library(shinyjs)
library(shinyDarkmode)
library(DT)
library(dplyr)
library(ggplot2)
library(plotly)
file_dir <- paste0(getwd(),"/Data/")
data_00<- read.csv(paste0(file_dir, "Dataeco", ".csv"),header = T)
