options(warn = -1) # suppress all warning messages generated by R

header = dashboardHeader(title = "Economic Pulse", titleWidth = 1450)

# Customizing Side-Bar Options and Drop Downs
sidebar = dashboardSidebar(disable = TRUE)

# Customizing Main-Panel and Outputs of the Dashboard
body = dashboardBody(
  
  use_darkmode(),
  # ~ Creates a logo for browser-tab.
  tags$head(
    tags$link(rel = "shortcut icon", href = "logo.ico")),
  
  # ~ Restricts display of error on the Dashboard. Output will be blank in case of error
  # @ Disable if you wish to see errors while developing the dashboards.
  tags$style(type="text/css", ".shiny-output-error { visibility: hidden; }", 
             ".shiny-output-error:before { visibility: hidden; }"),
  
  tabBox(id = "tabs", height = NULL , width = 13,
         
         # Home Tab for Inputs
         tabPanel( id="tab1", 
                   title = strong("DashBoard"), status = "primary",
                   height = NULL , width = 12,
                   fluidRow(box(
                     column(10,
                            selectInput(inputId="continent", label="Continent:", choices=unique(data_00$continent), selected="Oceania"))
                   ),
                   box(
                     column(12,dataTableOutput("data")),
                   )
                   
                   
                   ),
                   fluidRow(
                     box(column(12,plotlyOutput("fig_01"))),
                     
                     #plotOutput("pie"),
                     box(
                       column(12,
                              plotlyOutput("fig_02")),
                       #plotOutput("bar")
                     )
                   ),
                   fluidRow(
                     box(column(12,plotlyOutput("fig_03"))),
                     
                     #plotOutput("pie"),
                   )
                   
         ),
         
         tabPanel( id="tab2", 
                   title = strong("Data"),
                   height = NULL , width = 12,
                   fluidRow(box(
                     column(12,dataTableOutput("tab02")),
                   )
                   
                   
                   ),)
  )
)  


# Final Step for building the UI
dashboardPage(header, sidebar, body, skin = "yellow", title = "Economic Pulse")

